name: check
on: workflow_dispatch
jobs:
  x:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -qq -y lftp
      - env:
          U: ${{ secrets.FTP_USERNAME }}
          P: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c "set ftp:ssl-allow no; open -u \"$U\",\"$P\" ftp://82.25.87.207; cls -l vehicles-* *.php"
